server:
  port: 8082
  servlet:
    context-path: /api
spring:
  application:
    name: ms-products
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      routing-key: email_routing_key
      exchange: email_exchange
      default-receive-queue: ms-email


  datasource:
    url: jdbc:mysql://localhost:3306/ms_email
    username: root
    password: 1234
  jpa:
    open-in-view: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: challengecompass1@gmail.com
    password: gavzqxojumpvbfdb
    properties:
      mail:
        smtp:
          starttls:
            enable: true
        auth: true

logging:
  level:
    web: debug
