server:
  port: 8081
  servlet:
    context-path: /api
spring:
  application:
    name: ms-products

  datasource:
    url: jdbc:mysql://localhost:3306/challenge3
    username: root
    password: 1234
  jpa:
      open-in-view: true


  ## configuração do rabbitmq
  #rabbitmq:
  # host: localhost
  # port: 5672
  # username: guest
  # password: guest
#  listener:
#    simple:
#      retry:
#        enabled: true
#        max-attempts: 3
#        initial-interval: 5000
#        multiplier: 1
#        max-interval: 300000

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8080/api/eureka

logging:
  level:
    web: debug
