  server:
    port: 8080

  spring:
    application:
      name: api-gateway
    cloud:
      gateway:
        discovery:
          locator:
            enabled: true
            lower-case-service-id: true
        routes:
           - id: ms-products
             uri: http://localhost:8081
             predicates:
               - Path=/api/**
           - id: ms-notification
             uri: http://localhost:8082/
             predicates:
               - Path=/notification/**
           - id: ms-authorization
             uri: http://localhost:8083/
             predicates:
               - Path=/oauth/**
  logging:
    level:
      web: debug

