
server:
  port: 8083
  servlet:
    context-path: /oauth
spring:
  application:
    name: ms-authorization
  datasource:
    url: jdbc:mysql://localhost:3306/challenge3
    username: root
    password: 1234
  jpa:
    open-in-view: true

logging:
  level:
    web: debug